name: "Release"

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  GH_TOKEN: ${{ github.token }}

jobs:
  build-musl:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Install target toolchain
        run: |
          rustup target add x86_64-unknown-linux-musl

      - name: Install toolchain dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config musl-tools build-essential curl

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-musl --bin claudestine

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: musl
          retention-days: 1
          path: |
            target/x86_64-unknown-linux-musl/release/claudestine

  build-darwin:
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Install target toolchain
        run: |
          rustup target add aarch64-apple-darwin

      - name: Build
        run: |
          export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
          cargo build --release --target aarch64-apple-darwin --bin claudestine

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin
          retention-days: 1
          path: |
            target/aarch64-apple-darwin/release/claudestine

  release:
    runs-on: ubuntu-22.04
    needs:
      - build-musl
      - build-darwin

    permissions:
      contents: write

    steps:
      # this downloads all artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Rename Files
        run: |
          mv musl/claudestine linux-claudestine && \
          mv darwin/claudestine macos-claudestine

      - name: Create Release
        run: |
          gh release --repo LordSalmon/claudestine create "$GITHUB_REF_NAME" \
            macos-claudestine linux-claudestine --title "$GITHUB_REF_NAME"
